### ISSUE TITLE
Opencode não instala corretamente após atualização do pacote Launchy

### ISSUE THREAD

**Issue by rhandrade** [tray-tecnologia/opencode_theme#44]
Recentemente o pacote Launchy foi atualizado para a versão 2.5.0. Como o Opencode ainda não suporta as versões mais recentes do Ruby e nem limita a versão máxima do pacote, ocorre erro na instalação do Opencode.

Se alguém tiver esse problema faça o seguinte:

1. Instale a versão v2.3.3 do Ruby. Você pode baixar os executaveis para Windows x64 [aqui](https://dl.bintray.com/oneclick/rubyinstaller/ruby-2.3.3-x64-mingw32.7z) ou a x86 [aqui](https://dl.bintray.com/oneclick/rubyinstaller/ruby-2.3.3-i386-mingw32.7z). Para instalação no Linux, veja o artigo da Digital Ocean [aqui](https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rbenv-on-ubuntu-18-04-pt) e para instalação no macOs veja [esse](https://medium.com/qaninja/instalando-o-ruby-no-macos-435f451b86a8) post no Medium.
2. Após instalar o Ruby, execute o comando `gem install launchy` para instalar a versão do pacote Launchy.
3. Em seguida, execute o comando `gem install opencode_theme` para instalar o opencode normalmente.

**Comment by rhandrade** [comment]
Mais uma biblioteca foi atualizada, a Faraday, no dia 17/10/2020, para a versão 1.1 a qual subiu a versão mínima do Ruby para a 2.4 para rodar. Utilizem o procedimento abaixo para instalar ao invés do comentário acima.

1. Instale a versão v2.3.3 do Ruby. Você pode baixar a versão para Windows x64 [aqui ](https://dl.bintray.com/oneclick/rubyinstaller/ruby-2.3.3-x64-mingw32.7z) ou a x86 [aqui](https://dl.bintray.com/oneclick/rubyinstaller/ruby-2.3.3-i386-mingw32.7z).
2. Após instalar o Ruby, execute o comando `gem install faraday -v 1.0.1` para instalar a versão 1.0.1 do Faraday;
3. Em seguida execute o comando `gem install launchy -v 2.4.3` para instalar a versão 2.4.3 do pacote Launchy;
4. Em seguida, execute o comando `gem install opencode_theme` para instalar o opencode normalmente.

**Comment by RenanBrenio** [comment]
@rhandrade Cara, eu tentei essa solução mas ainda não consigo usar os comandos de download e watch do opencode. Eu instalei o ruby-2.3.3 usando rvm.

macOS Catalina 10.15.7
Ruby: v2.3.3-p222
OpencodeTheme: v:1.0.4
Operating System: x86_64-darwin19
HTTParty: v0.14.0
Launchy: v2.4.3

**Comment by rhandrade** [comment]
@RenanBrenio Qual o erro que acontece quando você utiliza o download e o watch?

**Comment by RenanBrenio** [comment]
@rhandrade O download agora está normal, porém o watch continua não funcionando e não printa nada no console, por consequência o o gulp --folder também está com o mesmo comportamento

**Comment by rhandrade** [comment]
@RenanBrenio Geralmente o watch só imprime algo no console se ele identificar que teve alguma modificação... Vc está usando o gulp para qual propósito?

**Comment by RenanBrenio** [comment]
@rhandrade Obrigado por estar me ajudando!

Estou usando o gulp para compilar os assets e na verdade ele está funcionando corretamente, inclusive subindo os arquivos assim que são gerados. 

Porém quando uso o $opencode watch sem ser pelo gulp, ele não observa nenhum tipo de arquivo nem imprime nenhum erro.

bundler: v1.17.3
faraday: v1.0.1
filewatcher: v1.1.1
launchy: v2.4.3
opencode_theme: v1.0.4

**Comment by rhandrade** [comment]
@RenanBrenio Magina... a beleza de um projeto open source é ter a comunidade se ajudando.

Verifiquei a versão do opencode e das dependências que estou usando e são as seguintes:

**_opencode_theme: 1.0.7.1_**
filewatcher: v1.1.1
github_api: 0.19.0
httparty: 0.14.0
launchy: 2.4.3
mimemagic: 0.3.5
rubyzip: 1.2.1
thor: 1.0.1
vcr: 6.0.0
webmock: 3.9.3

Vi agora que vc está usando a versão 1.0.4. Tentar baixar a versão mais recente do opencode_theme, a 1.0.7.1 e veja se funciona. Qualquer coisa tenta fazer a instalação do ruby via Homebrew https://medium.com/qaninja/instalando-o-ruby-no-macos-435f451b86a8

**Comment by RenanBrenio** [comment]
@rhandrade Eu tava bem confuso mesmo sobre a versão do opencode_theme, eu tentava atualizar para o v1.0.7.1 mas ele continuava no v1.0.4, isso por conta do arquivo /lib/opencode_theme/version.rb, assim que alterei consegui usar a nova versão.

 Porém caí no mesmo erro que #40 e a solução de mudar a versão do filewatcher para 0.5.4 funcionou.

**Comment by rhandrade** [comment]
@RenanBrenio Acredito que possa ser algo relacionado ao modo como o rvm faz a instalação do Ruby, por isso ao tentar atualizar não ia. Ai acredito que quando você modificou manualmente possa ter ficado resquícios da versão 1.0.4. 

Verifiquei que a ultima versão do opencode, a 1.0.7.1 corrige exatamente o erro reportado no #40. Consegui verificar nesse link https://my.diffend.io/gems/opencode_theme/1.0.7/1.0.7.1.  Qualquer coisa tenta fazer uma instalação limpa, removendo o ruby por completo e instalando novamente.

Não entendo o motivo de não existirem as outras alterações aqui no repositório do projeto, somente no rubygems.

Esse projeto aqui em ruby está abandonado. Estou estruturando um novo cli pra Tray feito em node.js, com libs mais recentes e melhores. Se tiver interesse, quando soltar uma versão minimamente estável lhe comunico.

**Comment by RenanBrenio** [comment]
@rhandrade Olá Rafael! Realmente sua sugestão de remover as versões do Ruby e RVM funcionaram, deve ter sido algum resquício mesmo ou falha na instalação que eu não consegui identificar, de qualquer maneira montei um passo a passo pra poder funcionar e vou deixar aqui pra quem estiver passando pelo mesmo problema e obrigado novamente pela ajuda! E tenho interesse no novo cli sim, me avise assim que disponível, obrigado!

### Instalar o RVM
```
$ gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
$ gpg-connect-agent --dirmngr 'keyserver --hosttable'
$ \curl -sSL https://get.rvm.io | bash -s stable
```

### Instalar Ruby v2.3.3
```
$ rvm pkg install openssl
$ rvm install 2.3.3 --with-openssl-dir=$HOME/.rvm/usr
```

### Instalar o opencode_theme
```
$ gem install faraday -v 1.0.1
$ gem install launchy -v 2.4.3
$ gem install opencode_theme
$ bundle install
```

**Comment by rankme-wilson** [comment]
Olá senhores, tudo bem? Tentei seguir os procedimentos acima porém não consigo instalar nada por nenhuma das linhas de comando... Por exemplo ao usar o comando: gem install opencode_theme , retorna o seguinte erro:
Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

**Comment by rhandrade** [comment]
@rankme-wilson Aparentemente esse é um erro relacionado a um arquivo/configuração faltando na instalação do gem. Da uma olhada nesses links, que estão no site oficial do Rubygem, com o passo a passo para resolver esse problema.

[SSL Certificate Updates](https://guides.rubygems.org/ssl-certificate-update/#installing-using-update-packages)
[Troubleshooting certificate errors](https://bundler.io/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html#troubleshooting-certificate-errors)

**Comment by oalexandre** [comment]
> Olá senhores, tudo bem? Tentei seguir os procedimentos acima porém não consigo instalar nada por nenhuma das linhas de comando... Por exemplo ao usar o comando: gem install opencode_theme , retorna o seguinte erro:
> Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

Olá, ví que você também publicou na outra issue, mas vale para quem chegar por aqui também.
Para quem usa ubuntu com a ajuda do @rhandrade criei um tutorial para auxiliar e automatizar este processo:
https://github.com/oalexandre/trayopencodeubuntu20

**Comment by brunosf** [comment]
Criei uma imagem em docker que configura o ambiente com o opencode e suas dependências, acho que pode ajudar.
https://github.com/brunosf/Boilerplate-Tray-Opencode

**Comment by rankme-wilson** [comment]
É isso mesmo @rhandrade, obrigado pela ajuda.

**Comment by AlissonCiprian0** [comment]
> Criei uma imagem em docker que configura o ambiente com o opencode e suas dependências, acho que pode ajudar.
> https://github.com/brunosf/Boilerplate-Tray-Opencode

Obrigado, você é um deus!

**Comment by AlissonCiprian0** [comment]
> > Olá senhores, tudo bem? Tentei seguir os procedimentos acima porém não consigo instalar nada por nenhuma das linhas de comando... Por exemplo ao usar o comando: gem install opencode_theme , retorna o seguinte erro:
> > Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
> 
> Olá, ví que você também publicou na outra issue, mas vale para quem chegar por aqui também.
> Para quem usa ubuntu com a ajuda do @rhandrade criei um tutorial para auxiliar e automatizar este processo:
> https://github.com/oalexandre/trayopencodeubuntu20

Olá! O script não funcionou pra mim por causa de um conflito com o libssl-dev. 

Pra resolver, antes de instalar o libssl1.0-dev, rodei um apt remove libssl-dev.

Atualmente, também foi necessário instalar o nokogiri na versão 1.8.0 antes de instalar o opencode_theme.
gem install nokogiri -v 1.8.0
gem install opencode_theme

Obrigado pelo script!

**Comment by diegosouz4** [comment]
Estou tendo problemas para executar o comando "gem install opencode_theme".

Microsoft Windows [versão 10.0.19041.1110]
(c) Microsoft Corporation. Todos os direitos reservados.

C:\Windows\system32>gem install opencode_theme
ERROR:  Error installing opencode_theme:
        The 'mimemagic' native gem requires installed build tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'

C:\Windows\system32>

**Comment by rhandrade** [comment]
@diegosouz4 Já peguei esse erro tbm... Tá um porre instalar o opencode. Segue o novo tutorial que fiz.

---

**1. Instalar o Ruby** 
Instale o Ruby 2.3.3 de acordo com a versão do Windows. O opencode não funciona bem com versões mais recentes 😕.
Segue os links para download:
- [32 bits](https://github.com/oneclick/rubyinstaller/releases/download/ruby-2.3.3/rubyinstaller-2.3.3.exe)
- [64 bits](https://github.com/oneclick/rubyinstaller/releases/download/ruby-2.3.3/rubyinstaller-2.3.3-x64.exe)


**2. Instalar o certificado para o Ruby 2.3.3**
- Acesse [essa página](https://bundler.io/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html#updating-ca-certificates) para baixar o certificado ou acesse [esse link](https://raw.githubusercontent.com/rubygems/rubygems/master/lib/rubygems/ssl_certs/rubygems.org/GlobalSignRootCA_R3.pem). Lembre-se de salvar como `.pem`;
- Rode o comando `gem which rubygems` para saber onde está instalado o Ruby;
- Abra a pasta `ssl_certs` no caminho indicado pelo comando acima;
    - O caminho será parecido no Windows com algo como `C:\Ruby23\lib\ruby\2.3.0\rubygems\ssl_certs`.
- Copie o certificado baixado acima para a pasta `ssl_certs`.


**3. Baixar e instalar o DevKit para o Ruby**
- Acesse [essa página](https://rubyinstaller.org/downloads/archives/) de arquivos de downloads do Ruby Installer;
- Baixe o arquivo DevKit:
    - [32 bits - DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe](https://github.com/oneclick/rubyinstaller/releases/download/devkit-4.7.2/DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe)
    - [64 bits - DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe](https://github.com/oneclick/rubyinstaller/releases/download/devkit-4.7.2/DevKit-mingw64-64-4.7.2-20130224-1432-sfx.exe)
- Extraia os arquivo para uma pasta;
    - **Atenção**: **não** deve ser extraido dentro da pasta onde foi instalado o Ruby!
    - Sugiro extrair para uma pasta no mesmo nível onde instalou o Ruby 2.3.3. Ex:
        ```
        C:\Ruby23\
        C:\Ruby-Devkit\
        ```
- Acesse a pasta onde extraiu o Devkit no passo anterior no cmd ou Powershell;
- Rode os comandos abaixo para fazer a instalação do DevKit:
    ```
    ruby dk.rb init
    ruby dk.rb install
    ```


**4. Baixar base de dados de tipos e configurar a variável de ambiente**
- Esse arquivo é importante pois será usado durante a instalação do `mimemagic` mais a frente;
- Baixe o arquivo contendo a base de tipos de arquivos da freedesktop.org [nesse link](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/raw/master/data/freedesktop.org.xml.in?inline=false);
- Renomeie o arquivo de `freedesktop.org.xml.in` para `freedesktop.org.xml`. Se sistema perguntar se deseja mudar a extensão, confirme;
- Configure a variável de ambiente `FREEDESKTOP_MIME_TYPES_PATH` para onde colocou o arquivo. Use o comando abaixo no cmd ou powershell com privilégios de administrador:
    ```sh
    setx FREEDESKTOP_MIME_TYPES_PATH "[caminho-arquivo]" 
    # Exemplo: setx FREEDESKTOP_MIME_TYPES_PATH "C:\Dev\freedesktop.org.xml"
    ```

**5. Instalar versões datada de pacotes necessários manualmente**
Algumas bibliotecas foram atualizadas e suas versões mais atuais não são compatíveis com o opencode. Instale manualmente as versões abaixo, executando cada comando separadamente:
```sh
gem install faraday -v 1.0.1
gem install launchy -v 2.4.3
gem install nokogiri -v 1.8.0
```

**6. Instalar o mimemagic** 
O mimemagic agora precisa do DevKit do Ruby para ser instalado corretamente. O comando é o mesmo para a instalação de pacotes Ruby, mas durante a instalação ele usará o arquivo baixado e configurado no passo 4. Para isso use o comando abaixo:
```sh
gem install mimemagic
```

**7. Instalar o opencode**
E agora, finalmente, é só instalar o opencode normalmente: 😐🎉
```sh
gem install opencode_theme
```

---
Eu estou desenvolvendo um novo CLI para a Tray feito do zero usando Node.js e TypeScript. Estou nos finalmentes dele e acho q nesse domingo já lanço uma versão alpha para quem quiser testar. Ele é 100% compatível com o opencode. Se quiser já deixa salvo ai para ir acompanhando segue o link: https://github.com/rhandrade/tray-theme

**Comment by rhandrade** [comment]
Pessoal, publiquei um novo CLI feito em Node.js para a Tray. Quem tiver interesse em testar e ajudar segue o link:
https://github.com/rhandrade/tray-theme

**Comment by AlissonCiprian0** [comment]
> Pessoal, publiquei um novo CLI feito em Node.js para a Tray. Quem tiver interesse em testar e ajudar segue o link:
> https://github.com/rhandrade/tray-theme

Cara, você é um deus!
Obrigado!!!

**Comment by diegosouz4** [comment]
@rhandrade  Obrigado, vou tentar aqui.

**Comment by diegosouz4** [comment]
@rhandrade Deu erro ao tentar usar o comando "gem install mimemagic", mesmo seguindo todos os passos.


```
C:\Ruby-Devkit>gem install mimemagic
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing mimemagic:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mimemagic-0.4.3/ext/mimemagic
C:/Ruby23-x64/bin/ruby.exe -rubygems C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/rake-10.4.2/bin/rake RUBYARCHDIR=C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/mimemagic-0.4.3 RUBYLIBDIR=C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/mimemagic-0.4.3
rake aborted!
Could not find MIME type database in the following locations: ["/usr/local/share/mime/packages/freedesktop.org.xml", "/opt/homebrew/share/mime/packages/freedesktop.org.xml", "/opt/local/share/mime/packages/freedesktop.org.xml", "/usr/share/mime/packages/freedesktop.org.xml"]

Ensure you have either installed the shared-mime-info package for your distribution, or
obtain a version of freedesktop.org.xml and set FREEDESKTOP_MIME_TYPES_PATH to the location
of that file.

Tasks: TOP => default
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/mimemagic-0.4.3 for inspection.
Results logged to C:/Ruby23-x64/lib/ruby/gems/2.3.0/extensions/x64-mingw32/2.3.0/mimemagic-0.4.3/gem_make.out

C:\Ruby-Devkit>
```

**Comment by rhandrade** [comment]
@diegosouz4 Depois que vc configurou a variável de ambiente no passo 4 você reiniciou o cmd/powershell para que a nova variável de ambiente fosse carregada? O erro que você postou mostra que ele não encontrou a base de dados do passo 4 na hora de fazer o build.

Para ver todas as variáveis que o foram carregadas faça o comando abaixo:
No cmd: `SET`
No Powershell: `dir env:`

Ai verifica se a `FREEDESKTOP_MIME_TYPES_PATH` esta na lista que ele exibir.

**Comment by diegosouz4** [comment]
@rhandrade Agora foi. Obrigado pela ajuda ^.^

**Comment by diegosouz4** [comment]
@rhandrade não consigo usar o comando "opencode configure API_KEY PASSWORD THEME_ID".
**Obs: usei a key, o password e theme_id certo. Só não coloquei aqui.**
```
D:\Diego\Loja teste\Poeme-se - Tray\opencode\poemese.commercesuite.com.br>opencode configure API_KEY PASSWORD THEME_ID 
[14:51:40] Error: Configuração [FALHOU]
Error Details:
D:\Diego\Loja teste\Poeme-se - Tray\opencode\poemese.commercesuite.com.br>
```

**Comment by rhandrade** [comment]
@diegosouz4 pode ser alguma instabilidade momentânea da Tray. Eles estão migrando a versão do jQuery e tá uma carroça esses dias. Eu tentei o configure aqui e foi normalmente. Qualquer coisa repete o comando `gem install opencode_theme`  que se tiver algum pacote que não instalou ele instala.

**Comment by thiagofloriano** [comment]
> Recentemente o pacote Launchy foi atualizado para a versão 2.5.0. Como o Opencode ainda não suporta as versões mais recentes do Ruby e nem limita a versão máxima do pacote, ocorre erro na instalação do Opencode.
> 
> Se alguém tiver esse problema faça o seguinte:
> 
> 1. Instale a versão v2.3.3 do Ruby. Você pode baixar os executaveis para Windows x64 [aqui](https://dl.bintray.com/oneclick/rubyinstaller/ruby-2.3.3-x64-mingw32.7z) ou a x86 [aqui](https://dl.bintray.com/oneclick/rubyinstaller/ruby-2.3.3-i386-mingw32.7z). Para instalação no Linux, veja o artigo da Digital Ocean [aqui](https://www.digitalocean.com/community/tutorials/how-to-install-ruby-on-rails-with-rbenv-on-ubuntu-18-04-pt) e para instalação no macOs veja [esse](https://medium.com/qaninja/instalando-o-ruby-no-macos-435f451b86a8) post no Medium.
> 2. Após instalar o Ruby, execute o comando `gem install launchy -v 2.4.3` para instalar a versão do pacote Launchy.
> 3. Em seguida, execute o comando `gem install opencode_theme` para instalar o opencode normalmente.

Os links para download do Ruby Installer estão com restrição de acesso.

**Comment by rhandrade** [comment]
@thiagofloriano Verifique esse [tutorial aqui acima](https://github.com/tray-tecnologia/opencode_theme/issues/44?_pjax=%23repo-content-pjax-container#issuecomment-890379690), ele possui os links novos. Aparentemente o pessoal do instalador migrou para o Github.

**Comment by thiagofloriano** [comment]
No início do ano consegui rodar em Windows 10 com Ruby 4.10.1 fazendo a instalação da gem com `--force`, mas agora nosso colega não conseguiu por causa do mimemagic que foi atualizado e a versão antiga foi descontinuada. Curioso que no Ubuntu consegui instalar numa boa.

**Comment by rhandrade** [comment]
@thiagofloriano Pode ser que no Ubuntu os repositórios ainda estão apontando para uma versão mais antiga do Ruby que ai permite fazer a instalação. Vai entender 🤔

**Comment by micheltechEr** [comment]
> @rhandrade não consigo usar o comando "opencode configure API_KEY PASSWORD THEME_ID".
> **Obs: usei a key, o password e theme_id certo. Só não coloquei aqui.**
> 
> ```
> D:\Diego\Loja teste\Poeme-se - Tray\opencode\poemese.commercesuite.com.br>opencode configure API_KEY PASSWORD THEME_ID 
> [14:51:40] Error: Configuração [FALHOU]
> Error Details:
> D:\Diego\Loja teste\Poeme-se - Tray\opencode\poemese.commercesuite.com.br>
> ```
> 
> Só estou conseguindo usar o comando de criar um theme novo.

Boa noite, eu também estou com o mesmo problema.

**Comment by rhandrade** [comment]
@micheltechEr Você poderia postar o erro que acontece? Eu testei aqui e estava funcionando. Não sei se foi uma instabilidade da Tray. Se puder dar mais detalhes posso te ajudar. 

Por acaso instalou o opencode recentemente?

**Comment by oalexandre** [comment]
Pessoal, a partir de um fork do @brunosf eu fiz algumas alterações.
https://github.com/oalexandre/tray-opencode-docker
Neste repositório subi um projeto que usando o Docker Compose cria toda a estrutura independente do seu ambiente, o que evita problemas com alterações e compatibilidade de bibliotecas.

Qualquer dúvidas, fico a disposição.

**Comment by fergerminare** [comment]
@oalexandre Tentei utilizar, não sei se fiz algo de errado. mas me apareceu estes erros:

`docker-compose up
[+] Running 1/0
 - Container tray_opencode  Created                                                                                0.0s
Attaching to tray_opencode
tray_opencode  | [18:43:48] Error: Configuração [FALHOU]
tray_opencode  | Error Details: Token de acesso inválido
tray_opencode  |  https://sites.google.com/a/tray.net.br/tecnologia/open-code/api#00001
tray_opencode  | Aguarde enquanto listamos os arquivos...
tray_opencode  | /var/lib/gems/2.7.0/gems/opencode_theme-1.0.7.1/lib/opencode_theme/cli.rb:137:in `download': undefined method `count' for nil:NilClass (NoMethodError)
tray_opencode  |        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
tray_opencode  |        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
tray_opencode  |        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
tray_opencode  |        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
tray_opencode  |        from /var/lib/gems/2.7.0/gems/opencode_theme-1.0.7.1/bin/opencode:22:in `<top (required)>'
tray_opencode  |        from /usr/local/bin/opencode:23:in `load'
tray_opencode  |        from /usr/local/bin/opencode:23:in `<main>'
tray_opencode  | config.yml não encontrado!
tray_opencode exited with code 1`

Se puder ajudar agradeço

**Comment by fergerminare** [comment]
> Pessoal, a partir de um fork do @brunosf eu fiz algumas alterações. https://github.com/oalexandre/tray-opencode-docker Neste repositório subi um projeto que usando o Docker Compose cria toda a estrutura independente do seu ambiente, o que evita problemas com alterações e compatibilidade de bibliotecas.
> 
> Qualquer dúvidas, fico a disposição.

Tentei utilizar, não sei se fiz algo de errado. mas me apareceu estes erros:

```
docker-compose up
[+] Running 1/0
 - Container tray_opencode  Created                                                                                0.0s
Attaching to tray_opencode
tray_opencode  | [18:43:48] Error: Configuração [FALHOU]
tray_opencode  | Error Details: Token de acesso inválido
tray_opencode  |  https://sites.google.com/a/tray.net.br/tecnologia/open-code/api#00001
tray_opencode  | Aguarde enquanto listamos os arquivos...
tray_opencode  | /var/lib/gems/2.7.0/gems/opencode_theme-1.0.7.1/lib/opencode_theme/cli.rb:137:in `download': undefined method `count' for nil:NilClass (NoMethodError)
tray_opencode  |        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
tray_opencode  |        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
tray_opencode  |        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
tray_opencode  |        from /var/lib/gems/2.7.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
tray_opencode  |        from /var/lib/gems/2.7.0/gems/opencode_theme-1.0.7.1/bin/opencode:22:in `<top (required)>'
tray_opencode  |        from /usr/local/bin/opencode:23:in `load'
tray_opencode  |        from /usr/local/bin/opencode:23:in `<main>'
tray_opencode  | config.yml não encontrado!
tray_opencode exited with code 1
```

Se puder ajudar, agradeço

**Comment by rhandrade** [comment]
@fergerminare Aparentemente ele não conseguiu encontrar o arquivo de configuração.

> config.yml não encontrado!
> tray_opencode exited with code 1

**Comment by fergerminare** [comment]
Com o do @brunosf eu consegui e baixou o tema. É primeira vez que estou criando/editando tema na Tray, pelo que vi num outro comentário seu o scss tem que ser compilado localmente pra ser enviado correto? Editando mesmo no painel da Tray a mudança não ocorre.

**Comment by rhandrade** [comment]
@fergerminare Isso mesmo. Compila o sass localmente e depois envia ela para a loja. Caso não queria usar o docker, pode usar esse outro CLI que eu desenvolvi https://github.com/rhandrade/tray-theme por enquanto. Ele faz o mesmo processo que o opencode_theme e está atualizado.

Em breve teremos novidades 😁🙃

**Comment by fergerminare** [comment]
> @fergerminare Isso mesmo. Compila o sass localmente e depois envia ela para a loja. Caso não queria usar o docker, pode usar esse outro CLI que eu desenvolvi https://github.com/rhandrade/tray-theme por enquanto. Ele faz o mesmo processo que o opencode_theme e está atualizado.
> 
> Em breve teremos novidades 😁🙃



> > @fergerminare Isso mesmo. Compila o sass localmente e depois envia ela para a loja. Caso não queria usar o docker, pode usar esse outro CLI que eu desenvolvi https://github.com/rhandrade/tray-theme por enquanto. Ele faz o mesmo processo que o opencode_theme e está atualizado.
> > Em breve teremos novidades grinupside_down_face
> 
> @fergerminare utilizando essa CLI você terá menos complicações.

@rhandrade @brunosf Obrigado pelas respostas, vou utilizar agora
