### ISSUE TITLE
Erro no opencode

### ISSUE THREAD

**Issue by Tsuiya** [tray-tecnologia/opencode_theme#45]
Estou tentando instalar o opencode em uma máquina windows, na página do opencode diz ser necessário a versão 2.3.3 do Ruby, porém é impossível de baixa-la, testei com a 2.4.3, porém o "Nekogiri" só é possível ser instalado com o Ruby na versão 2.5 ou maiores, testei com o 2.5.3, consegui instalar, porém, ao executar ocorre um erro.

`C:\Users\Daniel>gem install opencode_theme -v 1.0.7
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
Successfully installed mimemagic-0.4.3
Fetching: httparty-0.14.0.gem (100%)
When you HTTParty, you must party hard!
Successfully installed httparty-0.14.0
Fetching: thor-1.1.0.gem (100%)
Successfully installed thor-1.1.0
Fetching: opencode_theme-1.0.7.gem (100%)
Successfully installed opencode_theme-1.0.7
Parsing documentation for mimemagic-0.4.3
Installing ri documentation for mimemagic-0.4.3
Parsing documentation for httparty-0.14.0
Installing ri documentation for httparty-0.14.0
Parsing documentation for thor-1.1.0
Installing ri documentation for thor-1.1.0
Parsing documentation for opencode_theme-1.0.7
Installing ri documentation for opencode_theme-1.0.7
Done installing documentation for mimemagic, httparty, thor, opencode_theme after 5 seconds
4 gems installed

C:\Users\Daniel>opencode
Traceback (most recent call last):
        14: from C:/Ruby25-x64/bin/opencode:23:in `<main>'
        13: from C:/Ruby25-x64/bin/opencode:23:in `load'
        12: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/opencode_theme-1.0.7/bin/opencode:18:in `<top (required)>'
        11: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/opencode_theme-1.0.7/bin/opencode:8:in `fallback_load_path'
        10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/opencode_theme-1.0.7/bin/opencode:20:in `block in <top (required)>'
         9: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         8: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/opencode_theme-1.0.7/lib/opencode_theme/cli.rb:10:in `<top (required)>'
         6: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         5: from C:/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mimemagic-0.4.3/lib/mimemagic.rb:8:in `<top (required)>'
         3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mimemagic-0.4.3/lib/mimemagic/tables.rb:73:in `parse_database'
         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mimemagic-0.4.3/lib/mimemagic/tables.rb:69:in `open_mime_database'
         1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mimemagic-0.4.3/lib/mimemagic/tables.rb:69:in `open'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/mimemagic-0.4.3/lib/mimemagic/tables.rb:69:in `initialize': Is a directory @ rb_sysopen - C:/Ruby25-x64/msys64/usr/share/mime/packages (Errno::EISDIR)`

**Comment by honjoya** [comment]
Aguarde o Merge, irá rodar na versão 2.4 e 2.5 do ruby
https://github.com/tray-tecnologia/opencode_theme/pull/46

**Comment by Tsuiya** [comment]
Para quem precisa, já consegui resolver, basta alguns arquivos.

[Opencode.zip](https://github.com/tray-tecnologia/opencode_theme/files/6563146/Opencode.zip)

**Comment by Gabrielfelippe1** [comment]
> Para quem precisa, já consegui resolver, basta alguns arquivos.
> 
> [Opencode.zip](https://github.com/tray-tecnologia/opencode_theme/files/6563146/Opencode.zip)

Eu baixei o zip, rodei o comando opencode e me aparece a mesma mesma mensagem, além de baixar preciso realizar outra ação?

**Comment by rhandrade** [comment]
@Gabrielfelippe1 Verifica esse [comentário ](https://github.com/tray-tecnologia/opencode_theme/issues/44#issuecomment-890379690) que coloquei [nessa outra issue](https://github.com/tray-tecnologia/opencode_theme/issues/44) que tem um passo a passo de como instalar o Opencode com a versão 2.3.3 do Ruby. Infelizmente foi a única que consegui fazer o processo funcionar.

Ou se preferir pode o novo CLI que eu estou desenvolvendo, de maneira não oficial. Segue o link: https://github.com/rhandrade/tray-theme
