### ISSUE TITLE
Problema com o comando Watch

### ISSUE THREAD

**Issue by diegosouz4** [tray-tecnologia/opencode_theme#49]
Estou recebendo o seguinte erro ao tentar salvar
```
[06:37:50]Enviando: css/sass/_pagina-produto.scssC:/Ruby23-x64/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/protocol.rb:136:in `readuntil'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http/response.rb:29:in `read_new'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1437:in `block in transport_request'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1434:in `catch'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1434:in `transport_request'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1407:in `request'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1400:in `block in request'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:853:in `start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1398:in `request'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty/request.rb:118:in `perform'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty.rb:560:in `perform_request'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty.rb:512:in `put'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/opencode_theme-1.0.7.1/lib/opencode_theme/base_service.rb:83:in `send_asset'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/opencode_theme-1.0.7.1/lib/opencode_theme/cli.rb:300:in `block in send_asset'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/opencode_theme-1.0.7.1/lib/opencode_theme/cli.rb:408:in `show_during'   
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/opencode_theme-1.0.7.1/lib/opencode_theme/cli.rb:300:in `send_asset'    
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/opencode_theme-1.0.7.1/lib/opencode_theme/cli.rb:196:in `block in watch'        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/opencode_theme-1.0.7.1/lib/opencode_theme/cli.rb:334:in `block in watcher'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/filewatcher-1.1.1/lib/filewatcher/cycles.rb:40:in `block (2 levels) in trigger_changes'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/filewatcher-1.1.1/lib/filewatcher/cycles.rb:39:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/filewatcher-1.1.1/lib/filewatcher/cycles.rb:39:in `block in trigger_changes'
PS D:\Diego\Loja teste\Poeme-se - Tray\opencode\poemese.commercesuite.com.br\poeme-se v1 - github\poemese-tray-v1> opencode watch
[06:41:12]Enviando: css/sass/_pagina-produto.scssC:/Ruby23-x64/lib/ruby/2.3.0/net/protocol.rb:158:in `rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/protocol.rb:136:in `readuntil'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/protocol.rb:146:in `readline'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http/response.rb:29:in `read_new'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1437:in `block in transport_request'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1434:in `catch'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1434:in `transport_request'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1407:in `request'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1400:in `block in request'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:853:in `start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:1398:in `request'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty/request.rb:118:in `perform'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty.rb:560:in `perform_request'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/httparty-0.14.0/lib/httparty.rb:512:in `put'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/opencode_theme-1.0.7.1/lib/opencode_theme/base_service.rb:83:in `send_asset'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/opencode_theme-1.0.7.1/lib/opencode_theme/cli.rb:300:in `block in send_asset'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/opencode_theme-1.0.7.1/lib/opencode_theme/cli.rb:408:in `show_during'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/opencode_theme-1.0.7.1/lib/opencode_theme/cli.rb:300:in `send_asset'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/opencode_theme-1.0.7.1/lib/opencode_theme/cli.rb:196:in `block in watch'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/opencode_theme-1.0.7.1/lib/opencode_theme/cli.rb:334:in `block in watcher'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/filewatcher-1.1.1/lib/filewatcher/cycles.rb:40:in `block (2 levels) in trigger_changes'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/filewatcher-1.1.1/lib/filewatcher/cycles.rb:39:in `each'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/filewatcher-1.1.1/lib/filewatcher/cycles.rb:39:in `block in trigger_changes'
```

**Comment by rhandrade** [comment]
@diegosouz4 Aparentemente os arquivos scss não estão subindo no opencode, acredito que a Tray modificou alguma coisa que, ou os arquivos não são mais aceitos ou na hora de compilar da ruim.

Se você quiser usar o scss, sugiro fazer a compilação localmente, através do gulp com o [gulp-sass](https://www.npmjs.com/package/gulp-sass).
